_target_: config_schemes.model.ModelConfig
type: "CatBoost"
params: {
    iterations: 400,
    learning_rate: 0.05,
    loss_function: "Logloss",
    eval_metric: "F1",
    random_seed: 42,
    use_best_model: True,
    verbose: 50,
    task_type: "CPU",
    metric_period: 50,
}
transform_dataset: True
save_path: "../models/catboost_w_transformer.model"
transformer_save_path: "../models/transformer.pkl"
save_predict_path: "../models/catboost_w_transformer_predictions.csv"
